# Generated by Django 2.0.2 on 2019-02-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190209_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bodyy',
            new_name='body',
        ),
    ]
